# Generated by Django 5.2.16 on 2026-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_email_verified_profile_terms_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="company_address",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="address",
            name="company_eik",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="address",
            name="company_mol",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="company_vat_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="address",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
