# Generated by Django 5.2.3 on 2026-07-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_line",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_post_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash_on_delivery", "Наложен платеж")],
                default="cash_on_delivery",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost_bgn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("speedy_address", "Доставка до адрес"),
                    ("speedy_office", "До офис на Спиди"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="speedy_office_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="speedy_office_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
