# Generated by Django 5.2.3 on 2026-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_address_order_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal_bgn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_amount_bgn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_rate_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
