# Generated by Django 5.2.3 on 2026-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_invoice_creditnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("admin_order", "Admin order"),
                    ("customer_invoice", "Customer invoice"),
                    ("admin_confirmation", "Admin confirmation"),
                ],
                max_length=32,
            ),
        ),
    ]
