# Generated by Django 5.2.3 on 2026-08-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_emaillog_email_type"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="promotions.promotion",
            ),
        ),
    ]
