# Generated by Django 5.2.3 on 2026-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_company_address_order_company_eik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price_bgn",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
