# Generated by Django 5.2.3 on 2026-08-14 10:41

import uuid
from django.db import migrations, models


def seed_singleton_row(apps, schema_editor):
    # Order.generate_number() expects exactly one row to already exist
    # (looked up via .first(), not a fixed pk - see the model's own
    # docstring for why). Seeded at 0 so the first order placed after this
    # migration runs gets #1, not #0.
    OrderNumberSequence = apps.get_model("orders", "OrderNumberSequence")
    OrderNumberSequence.objects.create(last_value=0)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderitem_cost_price_bgn"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_singleton_row, migrations.RunPython.noop),
    ]
