# Generated by Django 5.2.16 on 2026-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_ordernumbersequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("admin_order", "Admin order"),
                    ("customer_invoice", "Customer invoice"),
                    ("admin_confirmation", "Admin confirmation"),
                    ("customer_rejection", "Customer rejection"),
                ],
                max_length=32,
            ),
        ),
    ]
