# Generated by Django 5.2.16 on 2026-08-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_emaillog_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Наложен платеж"),
                    ("bank_transfer", "Плащане по банков път"),
                ],
                default="cash_on_delivery",
                max_length=32,
            ),
        ),
    ]
