# Generated by Django 5.2.16 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("speedy_address", "Доставка до адрес"),
                    ("speedy_office", "До офис на Спиди"),
                    (
                        "pigeon_express_address",
                        "Доставка до адрес (Pigeon Express)",
                    ),
                    ("pigeon_express_office", "До офис на Pigeon Express"),
                    ("pigeon_express_locker", "До автомат на Pigeon Express"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_city_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_city_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_street_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_street_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_street_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_additional_info",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_office_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_office_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_reference_number",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_label_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="pigeon-express-labels/"
            ),
        ),
    ]
