# Generated by Django 5.2.17 on 2026-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_pigeon_express_package_height_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pigeon_express_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_expected_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_status_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_tracking",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="order",
            name="pigeon_express_tracking_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
