# Generated by Django 5.2.17 on 2026-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_pigeon_express_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pigeon_express_notified_stage",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("admin_order", "Admin order"),
                    ("customer_invoice", "Customer invoice"),
                    ("admin_confirmation", "Admin confirmation"),
                    ("customer_rejection", "Customer rejection"),
                    ("customer_shipping_update", "Customer shipping update"),
                ],
                max_length=32,
            ),
        ),
    ]
