# Generated by Django 5.2.16 on 2026-08-05 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promotions", "0002_promotion_max_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner_type",
                    models.CharField(
                        choices=[("product", "Product"), ("category", "Category")],
                        max_length=16,
                    ),
                ),
                ("image_path", models.CharField(max_length=1024)),
                (
                    "promotion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
