# Generated by Django 5.2.3 on 2026-08-02 08:23

from django.db import migrations, models


def backfill_sku(apps, schema_editor):
    """Every product needs a unique SKU before the unique constraint below can
    apply — none of the 91 imported products had one populated. Derive a
    stable code from external_id (already unique) rather than inventing one."""
    Product = apps.get_model("products", "Product")
    for product in Product.objects.filter(sku=""):
        product.sku = f"OC-{product.external_id}"
        product.save(update_fields=["sku"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier_code",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_url",
            field=models.URLField(blank=True, default="", max_length=1024),
        ),
        migrations.RunPython(backfill_sku, noop_reverse),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
