# Generated by Django 5.2.3 on 2026-08-02 08:28

import uuid

from django.db import migrations, models


def _generate_sku():
    # Frozen copy of products.models._generate_sku, which no longer exists
    # there (the sku field itself was later dropped entirely - see
    # 0006_remove_product_sku). Migrations are historical snapshots and
    # must stay replayable on their own; a callable default originally
    # serialized as a live reference to that function broke the moment it
    # was removed from the current model (confirmed directly: makemigrations
    # failed with AttributeError). Inlining it here, decoupled from the
    # live module, is the standard fix.
    return f"BR-{uuid.uuid4().hex[:8].upper()}"


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_supplier_code_product_supplier_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True,
                default=_generate_sku,
                max_length=128,
                unique=True,
            ),
        ),
    ]
