# Generated by Django 5.2.3 on 2026-08-02 08:28

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_supplier_code_product_supplier_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True,
                default=products.models._generate_sku,
                max_length=128,
                unique=True,
            ),
        ),
    ]
