# Generated by Django 5.2.16 on 2026-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
