# Generated by Django 5.2.3 on 2026-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_backfill_item_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
