# Generated by Django 5.2.3 on 2026-07-25 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpeedyOffice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("address", models.CharField(max_length=512)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
    ]
