# Generated by Django 5.2.3 on 2026-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="max_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
