# Generated by Django 5.2.16 on 2026-08-05 11:30
#
# Drops the old scope="user" value: target (product/category/global) and
# audience (the `user` FK) are now independent, so a "for this one client"
# promotion no longer needs its own scope — see promotions/models.py's
# updated comment. This migration converts existing scope="user" rows
# before removing "user" from the field's choices:
#   - had a product set  -> scope="product" (user FK untouched)
#   - no product set      -> scope="global"  (user FK untouched, "everything
#     for this client")
# category was never set on a scope="user" row (the old matching logic never
# checked it for that scope), so it's left as-is either way.

from django.db import migrations, models


def convert_user_scope_forward(apps, schema_editor):
    Promotion = apps.get_model("promotions", "Promotion")
    Promotion.objects.filter(scope="user", product__isnull=False).update(
        scope="product"
    )
    Promotion.objects.filter(scope="user", product__isnull=True).update(scope="global")


def convert_user_scope_backward(apps, schema_editor):
    # Best-effort only: a promotion converted forward is indistinguishable
    # afterward from one that was always scope=product/global with a user
    # set — there's no way to tell those apart on the way back, so this
    # deliberately does nothing rather than guess wrong.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_promotion_max_quantity"),
    ]

    operations = [
        migrations.RunPython(convert_user_scope_forward, convert_user_scope_backward),
        migrations.AlterField(
            model_name="promotion",
            name="scope",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("category", "Category"),
                    ("global", "Global"),
                ],
                default="product",
                max_length=16,
            ),
        ),
    ]
