# Generated by Django 6.0.7 on 2026-07-24 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_path", models.CharField(max_length=1024, unique=True)),
                ("to_path", models.CharField(max_length=1024)),
                ("status_code", models.PositiveIntegerField(default=301)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SEO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                ("keywords", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "canonical",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("robots", models.CharField(blank=True, default="", max_length=255)),
                ("open_graph", models.JSONField(blank=True, default=dict)),
                ("json_ld", models.JSONField(blank=True, default=list)),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
