# Generated by Django 6.0.7 on 2026-07-24 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "logo_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
