# Generated by Django 6.0.7 on 2026-07-24 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(default="Office Center BG", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="0700 45 095", max_length=64),
                ),
                ("currency", models.CharField(default="BGN", max_length=8)),
                ("language", models.CharField(default="bg", max_length=8)),
            ],
            options={
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
