# Generated by Django 5.2.17 on 2026-09-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="pigeon_express_pickup_office_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pigeon_express_pickup_office_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
